In [1]:
import numpy as np

In [9]:
a = [10,11,12,13,14,15]

In [10]:
import numpy as np

In [14]:
n_a = np.array(a)

In [15]:
n_a

array([10, 11, 12, 13, 14, 15])

In [16]:
n_a[0]

10

In [17]:
n_a[1]

11

In [18]:
last_index = len(n_a) - 1

In [19]:
n_a[last_index]

15

In [20]:
n_a[-1]

15

In [24]:
n_a[4]

14

In [25]:
n_a[-2]

14

In [30]:
n_a[1:-1]

array([11, 12, 13, 14])

In [31]:
n_a[0:3]

array([10, 11, 12])

In [32]:
n_a[3:6]

array([13, 14, 15])

In [33]:
n_a[2:4]

array([12, 13])

In [34]:
n_a[::2]

array([10, 12, 14])

In [35]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [36]:
n_c = np.concatenate([n_a, n_b])

In [37]:
np.sum(n_c)

690

In [38]:
np.max(n_c)

105

In [40]:
np.min(n_c)

10

In [45]:
np.mean(n_c)


57.5

In [46]:
np.average(n_c)

57.5